## tf.data service non-determinism due to SplitProvider races
The resulting elements are different depending on the number of workers used in the tf.data service. This is due to a *race condition on the split provider for dataset3*. The dataset graph was constructed to provoke that situation, consult [sources/pipeline.py](sources/pipeline.py) for details.

```
(tf28_orig) dan@thinkdan ~/eth/mthesis/tf-data-nondeterminism $ ./experiment.sh

Executing with 3 Workers
starting worker 1
starting worker 2
starting worker 3
starting pipeline.py
[1, 10106, 20209, 30313, 40417, 50518, 60619, 70900, 101004, 111105, 121207, 131308, 141410, 151511, 161612, 171714, 181815, 191902]
Epoch took: 1.074263334274292
[4, 10107, 20209, 30312, 40417, 50518, 60619, 90903, 101005, 111106, 121208, 131310, 141411, 151513, 161614, 171715, 181800, 191901]
Epoch took: 1.0400910377502441
[4, 10108, 20210, 30316, 40417, 50518, 60619, 90903, 101005, 111106, 121207, 131309, 141411, 151512, 161613, 171800, 181714, 191901]
Epoch took: 1.051285743713379
[4, 10106, 20209, 30313, 40417, 50518, 60619, 90903, 101005, 111107, 121208, 131310, 141411, 151512, 161614, 171715, 181800, 191901]
Epoch took: 1.0504143238067627
[0, 10402, 20301, 30104, 40208, 50713, 60503, 70605, 80809, 90906, 101018, 111112, 121219, 131314, 151507, 161615, 181816, 191910]
Epoch took: 1.0510694980621338
[0, 10106, 20215, 30316, 40417, 50518, 60619, 90901, 101002, 111104, 121203, 131305, 141407, 151508, 161609, 171710, 181811, 191913]
Epoch took: 1.0462357997894287
[0, 10107, 20215, 30316, 40417, 50518, 60619, 90901, 101002, 111105, 121203, 131310, 141404, 151511, 161606, 171712, 181808, 191913]
Epoch took: 1.0386323928833008

Executing with 1 Worker
starting worker 1
starting pipeline.py
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0656003952026367
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.04494047164917
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0345196723937988
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0266902446746826
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0371127128601074
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0482900142669678
[0, 10101, 20202, 30303, 40404, 50505, 60606, 70707, 80808, 90909, 101010, 111111, 121212, 131313, 141414, 151515, 161616, 171717, 181818, 191919]
Epoch took: 1.0358257293701172
```

### Env
The upstream tensorflow==2.8 was used.
```
(tf28_orig) dan@thinkdan ~/eth/mthesis/tf-data-nondeterminism $ python3 -c 'import tensorflow as tf; print(tf.__version__)'
2022-03-23 16:36:36.871561: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-23 16:36:36.871590: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2.8.0
(tf28_orig) dan@thinkdan ~/eth/mthesis/tf-data-nondeterminism $ python3 --version
Python 3.9.10
```
